### ISSUE TITLE
Add Field Validation in Backend

### ISSUE THREAD

**Issue by mathanraj0601** [subh05sus/ThalaForReason#3]
#### Description
- Though Frontend has validation it is good to have validation in the backend

#### Plan
- [x] Adding similar field validation in Backend

**Comment by mathanraj0601** [comment]
I am excited to work on this @subh05sus  Can you assign me this for SWOC24?

**Comment by SadanandMiskin** [comment]
@mathanraj0601 what validation you mean? Is it only checking whether the email is correct? or is it validation of data from database?

**Comment by sanketshinde3001** [comment]
hello , i have work on this project of my own . I have added multiple varification to check that input is related to dhoni or thala . 
so assign me this issue , i'll make it perfect

**Comment by mathanraj0601** [comment]
```   js
const question = req.body.query;
```

HI @SadanandMiskin, There is no check for the body. query in the backend server.js  so it can be empty if we hit API directly,

**Comment by subh05sus** [comment]
@sanketshinde3001 you need to raise an issue first
to start working on that project, else your marks won't be added sadly

**Comment by sanketshinde3001** [comment]
@subh05sus yes
At that moment i don't know about it
But later i raise issue for that... 
You xan check it out

**Comment by mathanraj0601** [comment]
That great @subh05sus . Update you with a PR soon
